module.exports = (brandname) => {
  let target = brandname;
  const list = 
  [ {'brand':'DKNY','en':'DKNY'},
  {'brand':'H&M','en':'H&M'},
  {'brand':'GANNI','en':'GANNI'},
  {'brand':'구찌','en':'Gucci'},
  {'brand':'골든구스','en':'Golden goose'},
  {'brand':'디올','en':'Dior'},
  {'brand':'돌체앤가바나','en':'Dolce & Gabbana'},
  {'brand':'라코스테','en':'Lacoste'},
  {'brand':'레페토','en':'Repetto'},
  {'brand':'로로피아나','en':'Loro Piana'},
  {'brand':'로샤스','en':'Rochas'},
  {'brand':'로에베','en':'Loewe'},
  {'brand':'로저비비에','en':'Roger Vivier'},
  {'brand':'롱샴','en':'Longchamp'},
  {'brand':'루이비통','en':'Louis Vuitton'},
  {'brand':'마놀로블라닉','en':'Manolo Blahnik'},
  {'brand':'마르니','en':'Marni'},
  {'brand':'막스마라','en':'Max Mara'},
  {'brand':'멀버리','en':'Mulberry'},
  {'brand':'몽클레어','en':'Moncler'},
  {'brand':'무스너클','en':'Moose Knuckles'},
  {'brand':'미우미우','en':'Miu Miu'},
  {'brand':'메종마르지엘라','en':'Maison Margiela'},
  {'brand':'바버','en':'Barbour'},
  {'brand':'발리','en':'Bally'},
  {'brand':'발렌시아가','en':'Balenciaga'},
  {'brand':'발렌티노','en':'Valentino'},
  {'brand':'버버리','en':'Burberry'},
  {'brand':'베르사체','en':'Versace'}, 
  {'brand':'보테가베네타 ','en':'Bottega veneta'},
  {'brand':'불가리','en':'Bulgari'},
  {'brand':'브리오니','en':'Brioni'},
  {'brand':'브루넬로쿠치넬리','en':'Brunello Cucinelli'},
  {'brand':'비비안웨스트우드','en':'Vivienne Westwood'},
  {'brand':'산드로','en':'Sandro'},
  {'brand':'생로랑','en':'Yves Saint Laurent'},
  {'brand':'샤넬','en':'Chanel'},
  {'brand':'셀린느','en':'Celine'},
  {'brand':'셀프포트레이트','en':'Self-Portrait'},
  {'brand':'스텔라매카트니','en':'Stella McCartney'},
  {'brand':'스튜어트와이츠먼','en':'Stuart Weitzman'},
  {'brand':'아디다스','en':'Adidas'},
  {'brand':'아르켓','en':'Arket'},
  {'brand':'아크네스튜디오','en':'Acne studios'},
  {'brand':'아크네','en':'Acne studios'},
  {'brand':'안느퐁텐','en':'Anne fontaine'},
  {'brand':'알렉산더맥퀸','en':'Alexander mcqueen'},
  {'brand':'에르메네질도제냐','en':'Ermenegildo Zegna'},
  {'brand':'에르메스','en':'Hermes'},
  {'brand':'에스까다','en':'Escada'},
  {'brand':'에트로','en':'Etro'},
  {'brand':'올세인츠','en':'All saints'},
  {'brand':'이브살로몬','en':'Yves Salomon'},
  {'brand':'이세이미야케','en':'Issey Miyake'},
  {'brand':'이자벨마랑','en':'Isabel Marant'},
  {'brand':'이자벨마랑에뚜왈','en':'Isabel Marant Etoile'},
  {'brand':'일레븐티','en':'Eleventy'},
  {'brand':'자라','en':'ZARA'},
  {'brand':'지미추','en':'Jimmy Choo'},
  {'brand':'지방시','en':'Givenchy'},
  {'brand':'지안비토 로시','en':'Gianvito rossi'},
  {'brand':'질샌더','en':'Jil Sander'},
  {'brand':'주세페자노티','en':'Giuseppe Zanotti'},
  {'brand':'카렌밀런','en':'Karen Millen'},
  {'brand':'코치','en':'Coach'},
  {'brand':'끌로에','en':'Chloe'},
  {'brand':'캐롤리나헤레라','en':'Carolina herrera'},
  {'brand':'크리스찬루부탱','en':'Christian louboutin'},
  {'brand':'처치스','en':"Church's"},
  {'brand':'테드베이커','en':'Ted Baker'},
  {'brand':'토리버치','en':'Tory Burch'},
  {'brand':'토즈','en':'Tods'},
  {'brand':'톰브라운','en':'Thom Browne'},
  {'brand':'톰포드','en':'Tom Ford'},
  {'brand':'페라가모','en':'Ferragamo'},
  {'brand':'펜디','en':'Fendi'},
  {'brand':'폴스미스','en':'Paul Smith'},
  {'brand':'프라다','en':'Prada'},
  {'brand':'핑코','en':'Pinko'},
  {'brand':'훌라','en':'Furla'} ];
  console.log(brandname === list[54].brand)
  console.log('****뭐가 문제인 거임', brandname, list[54].brand);
  const matchedBrand = list.find((ele) => ele.brand === target);
  if (matchedBrand) return matchedBrand.en;
  return target;
};